[build-system]
requires = ["setuptools>=75", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "voicegpt"
version = "0.1.0"
requires-python = ">=3.12"

dependencies = [
  "openai",
  "pyttsx3",
  "speechrecognition",
  "python-dotenv",
  "pyaudio"
]

[project.scripts]
voicegpt = "voicegpt.__main__:main"
